// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk6zWLQK5-1Hs2i4XRJrZTk0soYvBbrsA',
    appId: '1:945112694996:android:ccc1c669cb6d629cfd7b41',
    messagingSenderId: '945112694996',
    projectId: 'nature-of-kyrgyzstan',
    storageBucket: 'nature-of-kyrgyzstan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPum5H6NB6AJKrrH6uz8JRg45eBIYd5yo',
    appId: '1:945112694996:ios:271caeb8e5e9ff87fd7b41',
    messagingSenderId: '945112694996',
    projectId: 'nature-of-kyrgyzstan',
    storageBucket: 'nature-of-kyrgyzstan.appspot.com',
    iosClientId: '945112694996-d2957cc6g8mk4i7cfljukffhq2smq97a.apps.googleusercontent.com',
    iosBundleId: 'com.example.natureOfKyrgyzstan',
  );
}
