/// Flutter icons BottomNavIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BottomNavIcons
///      fonts:
///       - asset: fonts/BottomNavIcons.ttf
///
///
///
// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class BottomNavIcons {
  BottomNavIcons._();

  static const _kFontFam = 'BottomNavIcons';
  static const String? _kFontPkg = null;

  static const IconData plant_icon =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData red_book_icon =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
